export const SET_PRICE = "SET_PRICE";
export const SET_ORDER_NUMBER = "SET_ORDER_NUMBER";
export const SET_BUN_STATUS = "SET_BUN_STATUS";
export const ADD_TO_CONSTRUCTOR = "ADD_TO_CONSTRUCTOR"
export const DELETE_FROM_CONSTRUCTOR = "DELETE_FROM_CONSTRUCTOR"
export const SET_ING_STATUS = "SET_ING_STATUS";
export const CONSTRUCTOR_REPLACE = "CONSTRUCTOR_REPLACE"
